Player.onPlayerSpawn(function (player) {
    Player.give(player, Data.itemPicker(MinecraftItemTypes.Mace), 10, 1)
    Player.give(player, Data.itemPicker(MinecraftItemTypes.GoldenApple), 9, 32)
    Player.give(player, Data.itemPicker(MinecraftItemTypes.WindCharge), 8, 64)
    Player.give(player, Data.itemPicker(MinecraftItemTypes.Shield), 7, 1)
    Player.give(player, Data.itemPicker(MinecraftItemTypes.NetheriteAxe), 6, 1)
    Player.give(player, Data.itemPicker(MinecraftItemTypes.NetheriteSword), 5, 1)
    Player.give(player, Data.itemPicker(MinecraftItemTypes.NetheriteHelmet), 4, 1)
    Player.give(player, Data.itemPicker(MinecraftItemTypes.NetheriteChestplate), 3, 1)
    Player.give(player, Data.itemPicker(MinecraftItemTypes.NetheriteLeggings), 2, 1)
    Player.give(player, Data.itemPicker(MinecraftItemTypes.NetheriteBoots), 1, 1)
    System.runTimeout(20, function () {
        Player.setTitle(player, "GET READY!")
        Player.updateSubtitle(player, "5")
        System.pause(20)
        Player.updateSubtitle(player, "4")
        System.pause(20)
        Player.updateSubtitle(player, "3")
        System.pause(20)
        Player.updateSubtitle(player, "2")
        System.pause(20)
        Player.updateSubtitle(player, "1")
        System.pause(20)
        Player.setTitle(player, "GO!", "", 0, 1, 2)
    })
})
